[package]
name = "log-device"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait.workspace = true
thiserror.workspace = true
bytes.workspace = true
derive_builder.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
tokio-uring = { version = "0.5.0" }